apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opr-paas-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ApplyOutOfSyncOnly=true
spec:
  generators: []
  template:
    metadata:
      name: 'paas-{{paas}}-capability-argocd'
    spec:
      destination:
        namespace: '{{paas}}-argocd'
        server: 'https://kubernetes.default.svc'
      project: '{{paas}}'
      source:
        kustomize:
          commonLabels:
            capability: argocd
            clusterquotagroup: '{{requestor}}'
            paas: '{{paas}}'
            service: '{{service}}'
            subservice: '{{subservice}}'
        path: paas-capabilities/argocd
        repoURL: 'https://gitlab.com/BenoitSchipper/crc-benoit-sebas.git'
        targetRevision: main
      syncPolicy:
        automated:
          selfHeal: true
