---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  name: user-ca-bundle
  namespace: argocd
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"  # Generates SSL Certs