apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alert-routing-edit
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - alertmanagers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - alertmanagers/finalizers
    verbs:
      - update
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - alertmanagers/status
    verbs:
      - get
